version: '3'
services:

  registry:
    image: registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data

  web:
    image: localhost:5000/webserver
    build: ./web
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: lb3
    ports:
      - "3306:3306"

  admin:
    image: adminer
    ports:
      - "8000:8080"